# -*- coding: utf-8 -*-
"""eda_automation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aDnmR8YhoarQ9OcME0AgnWWTNoq6e4TK
"""

import pandas as pd
import matplotlib.pyplot as plt

customers = pd.read_csv("df_Customers.csv")
orders    = pd.read_csv("df_Orders.csv")
items     = pd.read_csv("df_OrderItems.csv")
payments  = pd.read_csv("df_Payments.csv")
products  = pd.read_csv("df_Products.csv")

orders["order_purchase_timestamp"] = pd.to_datetime(
    orders["order_purchase_timestamp"],
    errors="coerce"
)

df = orders.merge(customers, on="customer_id", how="left") \
           .merge(items, on="order_id", how="left") \
           .merge(products, on="product_id", how="left") \
           .merge(payments, on="order_id", how="left")

df = df.dropna(subset=["price", "shipping_charges"])

df["total_sale"] = df["price"] + df["shipping_charges"]
df["month"] = df["order_purchase_timestamp"].dt.to_period("M").astype(str)
df["year"] = df["order_purchase_timestamp"].dt.year

df["product_category_name"] = df["product_category_name"].fillna("Unknown")
df["customer_city"] = df["customer_city"].fillna("Unknown")
df["customer_state"] = df["customer_state"].fillna("Unknown")
df["payment_type"] = df["payment_type"].fillna("Unknown")

total_revenue = df["total_sale"].sum()
total_orders = df["order_id"].nunique()
total_customers = df["customer_id"].nunique()
delivered_orders = df[df["order_status"] == "delivered"]["order_id"].nunique()
aov = total_revenue / total_orders
print("✅ TOTAL REVENUE:", round(total_revenue, 2))
print("✅ TOTAL ORDERS:", total_orders)
print("✅ TOTAL CUSTOMERS:", total_customers)
print("✅ DELIVERED ORDERS:", delivered_orders)
print("✅ AOV:", round(aov, 2))

monthly_revenue = df.groupby("month")["total_sale"].sum().reset_index()

monthly_revenue.to_csv("monthly_revenue_python.csv", index=False)
df.to_csv("cleaned_ecommerce_master.csv", index=False)
print("✅ Saved: cleaned_ecommerce_master.csv")
print("✅ Saved: monthly_revenue_python.csv")

plt.figure(figsize=(12,5))
plt.plot(monthly_revenue["month"], monthly_revenue["total_sale"], marker="o")
plt.xticks(rotation=90)
plt.title("Monthly Revenue Trend")
plt.xlabel("Month")
plt.ylabel("Revenue")
plt.tight_layout()
plt.show()